locals {
  ecs_task_definition_name             = "sample-ecs-task"
  ecs_cluster_name                     = "sample-ecs-cluster"
  ecs_service_name                     = "sample-ecs-service"
  ecs_service2_name                    = "sample-ecs-service2"
  ecs_capacity_provider_name           = "sample-capacity-provider"
  ecs_security_group_name              = "sample-ecs-security-group"
  autoscaling_group_name               = "sample-asg-ecs-cluster"
  launch_template_name                 = "sample-launch-template"
  lb_name                              = "sample-lb"
  lb_target_group_name                 = "sample-lb-target-group"
  lb_target_group_sub_name             = "sample-lb-target-group-sub"
  lb2_name                             = "sample-lb2"
  lb2_target_group_name                = "sample-lb2-target-group"
  lb2_target_group_sub_name            = "sample-lb2-target-group-sub"
  lb_security_group_name               = "sample-lb-security-group"
  task_execution_iam_role_name         = "SampleEcsTaskExecutionRole"
  task_iam_role_name                   = "SampleEcsTaskRole"
  task_role_policy_name                = "sample-task-role-policy"
  s3_name                              = "sample-ecs-s3"
  codedeploy_app_name                  = "sample-code-deploy-app"
  codedeploy_deployment_group_bg_name  = "sample-code-deploy-app-group-bg"
  codedeploy2_app_name                 = "sample-code-deploy2-app"
  codedeploy2_deployment_group_bg_name = "sample-code-deploy2-app-group-bg"
  codepipeline_iam_role_name           = "CodePipelineServiceRole"
  codepipeline_name                    = "sample-code-pipeline"
  codepipeline2_name                   = "sample-code-pipeline2"
}
